### ISSUE TITLE
`method_missing': undefined method `convert_environment'

### ISSUE THREAD

**Issue by marcotama** [asciidoctor/asciidoctor-latex#81]
Hi,

First of all, thanks for all the work on this package!

I am trying to compile a formula within an `env.equationalign` environment, but I get an error.

Minimum example:
```adoc
[env.equationalign]
--
P(C=c|G=g) & = \frac{P(C=c,G=g)}{P(G=g)} & \text{(Bayes theorem)} \\
& = \frac{\sum_{b \in B} P(C=c,G=g,B=b)}{P(G=g)} & \text{(Law of total probability)} \\
& = \frac{\sum_{b \in B} P(C=c|G=g,B=b) \cdot P(G=g,B=b)}{P(G=g)} &\text{(Bayes theorem)} \\
& = \frac{\sum_{b \in B} P(C=c|G=g,B=b) \cdot P(G=g) \cdot P(B=b)}{P(G=g)} \quad&\text{($B$ and $G$ are independent)} \\
& = \frac{P(G=g) \cdot \sum_{b \in B} P(C=c|G=g,B=b) \cdot P(B=b)}{P(G=g)} &\text{(Factor out $P(G=g)$)} \\
& = \sum_{b \in B} P(C=c|G=g,B=b) \cdot P(B=b) &\text{(Simplify num. and denom.)}
--
```

and the error is (with `--trace`):

```
$ asciidoctor-latex -a stylesheet=asciidoctor.css -a stylesdir=styles/ "example.adoc" -b html -o "example.html" --trace
/Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:1306:in `method_missing': undefined method `convert_environment' for #<Asciidoctor::Converter::Html5Converter:0x00007f9a2500ec88> (NoMethodError)
Did you mean?  convert_inline_menu
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/converter.rb:388:in `convert'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:88:in `convert'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:227:in `convert_document'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb:84:in `convert'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
        from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-latex-1.5.0.17.dev/bin/asciidoctor-latex:20:in `<top (required)>'
        from /usr/local/bin/asciidoctor-latex:22:in `load'
        from /usr/local/bin/asciidoctor-latex:22:in `<main>'
```

Am I doing something wrong?

I am using:
```bash
$ asciidoctor-latex --version
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
I don't believe this converter / extension is compatible with Asciidoctor 2.

**Comment by marcotama** [comment]
Ok! Is there any alternative to get these aligned, multiline equations? I could not find it out through the documentation.

By the way, I had tried the above after updating to `2.0.10`, getting the error and rolling back to `1.5.8` and had the same problem. However, after uninstalling asciidoctor and reinstalling version `1.5.8`, it worked.

**Comment by mojavelinux** [comment]
> Is there any alternative to get these aligned, multiline equations? I could not find it out through the documentation.

I don't know the answer to that question. Perhaps someone else who is using it does.
